### ISSUE TITLE
Question about the ARGO 3D tracking competition

### ISSUE THREAD

**Issue by mengde-cmd** [argoai/argoverse-api#129] opened 2020-05-13 07:03 UTC
Hi:
  My team and I are very interested in your 3D tracking competition. We think this competition is of great significance to promote the research of target tracking. We have participated in your competition and submitted the results.
 **But there are still some problems we did not figure out**：

1. What’s the meaning of C: and P: in the C:MOTA and P:MOTA?
2. Why the Leaderboard did not seem to be updated ever hour as it‘s described in the Evaluation page？And, there are only 17 teams in the board while my team ranking is 99999.0.

Thanks!!
Mengde

**Comment by janesjanes** [comment] 2020-05-13 16:24
Hi mengde-cmd ,

Thanks for your interests in our tracking competition!

C refers to Car while P refers to Pedestrian categories. We compute MOTA separatedly for each category.

And the leaderboard should be updated now, sorry about that the server was down. Note that this ranking might change in the future when other entries change,

Feel free to ping us here if you have any questions or issue with the submission

**Comment by mengde-cmd** [comment] 2020-05-18 02:18
Hi janesjanes，

Thanks for your reply，and the ranking result was displayed correctly 4 days ago.

But there were two more questions we encountered, when we submitted new results:

1. The ranking result of our new submission in the "My submission" page was founded be 99999.0 again, when we clicked the link of "Result File". It appeared that this problem could result in that the ranking result would not be updated though we had a better result.

2. Our latest submission has been evaluated for about 22 hours, and it is still in running state until now.

We look forward to your early reply!

Thanks!

**Comment by janesjanes** [comment] 2020-05-18 03:13
Hi Mengde-cmd,

For the first issue, don't worry about the average ranking value in the results file, that's simply a placeholder and won't be used in the final score. The correct value will be updated once the submission is shown on the leaderboard. 

And if I understand correctly, the problem is that you had a better results that won't be shown on the leaderboard, correct? This is the problem that we are looking into currently with the evalai team, and once the fix is up, there will be an option for you to pick which single submission to show to the leaderboard. 

As for the currently running evaluation, let me look into that and I'll get back to you.

Thanks for your patience

**Comment by janesjanes** [comment] 2020-05-18 04:37
btw while we are waiting for the fix, if there's any specific submission you would like to show on the leaderboard, let me know and we can switch that one in manually (but we only allow one entry on the leaderboard per team). 

For now, you can just send me the team name and submission number that you want on the leaderboard to patsorn.sangkloy@gmail.com

**Comment by janesjanes** [comment] 2020-05-25 22:27
The fix is now live, you can now see an option to pick which submission to show to the public leaderboard. We also sent you an email regarding the submission issue. So I'm closing this for now, but let us know if you have any other issue,

**Closed by janesjanes** 2020-05-25 22:27 UTC
